################
### Language ###
################
language: bash

################
### Services ###
################
services:
  - docker

#####################
### Notifications ###
#####################
notifications:
  email: false

##################
### Deployment ###
##################
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master

######################
### Version Matrix ###
######################
matrix:
  include:
    - name: "Waterfall 1.14"
      env:
        - WATERFALL_VERSION=1.14
    - name: "Waterfall 1.13"
      env:
        - WATERFALL_VERSION=1.13
    - name: "Waterfall 1.12"
      env:
        - WATERFALL_VERSION=1.12
    - name: "Waterfall 1.11"
      env:
        - WATERFALL_VERSION=1.11
