version: '3.7'

services:

  waterfall:
    image: felixklauke/waterfall
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
    volumes:
      - ./logs:/opt/waterfall/server/logs
      - ./plugins:/opt/waterfall/server/plugins
